### ISSUE TITLE
File folder viewer does not only displays 7 saved paths

### ISSUE THREAD

**Issue by ryankuykendall** [Yqnn/svg-path-editor#113]
<img width="1693" alt="image" src="https://github.com/Yqnn/svg-path-editor/assets/30282/74c3413b-d344-4e25-8e9b-0da2e1344962">

When a user saves more than seven paths, they are unable to scroll through all of their saved paths in the file folder modal. Screenshot attached showing modal as well as nine objects in local storage.

**Comment by kuubeu** [comment]
Works for me:

![proof it works](https://github.com/Yqnn/svg-path-editor/assets/46360290/a2a0a235-545c-4405-a8bf-aeaad42d9de4)

Can you check what the last 2 entries (8 & 9) in your DB are?

**Comment by ryankuykendall** [comment]
Weird. 8 & 9 from the original screen shot could not be scrolled into view. But when I try to repro after adding additional saved paths (up to ten it works.) Now I can't get it to repro.

The 8 & 9 entries had the four fields:

 - changeDate
 - creationDate
 - name
 - path

I'll close this since I don't have repro steps to get it back into the state I was seeing. Thanks!
