### ISSUE TITLE
Enhancement: add a "New" button to start an empty canvas

### ISSUE THREAD

**Issue by vishnuharidas** [Yqnn/svg-path-editor#13]
Nice tool. 

I wanted to get rid of the sword :crossed_swords: image and start fresh with a blank canvas, but couldn't find the most expected "new" or "clear" button. After walking around, I realized that I can clear the contents of the "PATH" window to clear the canvas.

It will be good to add a **clear :x:** or **new :memo:** option where the users can easily clear the preset sword :crossed_swords: and start an empty canvas.

**Comment by Yqnn** [comment]
Done in last update.
