### ISSUE TITLE
Suggestion: Optimize relative / absolute

### ISSUE THREAD

**Issue by justingolden21** [Yqnn/svg-path-editor#132]
Instead of convert all to relative or all to absolve, if there was a third button to optimize, that would be helpful. I realize it's not as easy as checking each individual command since sometimes it depends on adjacent commands (for example lines in a row).

A bonus (but certainly not expected) would be to convert all horizontal and vertical `l` to `h` and `v`, and another would be to check for `z` when a path is already closed and if it ends in a `l`, `h`, or `v` then delete that command, else delete the `z`.

**Comment by Yqnn** [comment]
Done in #136
