### ISSUE TITLE
[Compatibility] App doesn't work

### ISSUE THREAD

**Issue by Tinhone** [Yqnn/svg-path-editor#134]
### Body

When I want to open the web page, there's nothing on the page.
当我想要打开网页时，网页上什么都没有。

According to this [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#browser_compatibility), personally, I think it's a compatibility issue.
根据此 [MDN 页面](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#browser_compatibility)，我个人认为这是一个兼容性问题。

### Repro

1. Go to https://yqnn.github.io/svg-path-editor/
2. The problem arises immediately

\--------

1. 前往 https://yqnn.github.io/svg-path-editor/
2. 问题即刻出现

### Possible Solutions

Adjusting polyfills settings, to enable it to be processed [private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties).
调整 Polyfills 设置，使其能够处理 [Private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties)。

### Other

Browser:
浏览器：
Mozilla Firefox v88.0

Log:
控制台日志：
```
Uncaught SyntaxError: private fields are not currently supported [polyfills.5820c91972767167.js:1:486](https://yqnn.github.io/svg-path-editor/polyfills.5820c91972767167.js)
Uncaught SyntaxError: private fields are not currently supported [main.67aed32d0b64c21e.js:1:38883](https://yqnn.github.io/svg-path-editor/main.67aed32d0b64c21e.js)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于来自无效的域名，已拒绝 Cookie “_ga_1BBJSPSKQ9”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 2 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于来自无效的域名，已拒绝 Cookie “_ga_1BBJSPSKQ9”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于来自无效的域名，已拒绝 Cookie “_ga”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于来自无效的域名，已拒绝 Cookie “_ga_1BBJSPSKQ9”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 2 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于来自无效的域名，已拒绝 Cookie “_ga_1BBJSPSKQ9”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
由于 Cookie “_ga_1BBJSPSKQ9”缺少“SameSite”属性，且该属性的默认值为“SameSite=Lax”，已将“SameSite”的策略设为“Lax”。 [js:333:1445](https://www.googletagmanager.com/gtag/js?id=G-1BBJSPSKQ9)
```

**Comment by Yqnn** [comment]
svg-path-editor is build with Angular framework which only supports the 2 most recent versions of each browsers:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/0782224f-3ca7-4ea8-b7e2-0e423c832b51">
Firefox 88.0 is more than 3 years old, such an old browser can't be supported anymore.

All the previous releases are available on the `gh-pages` branch: https://github.com/Yqnn/svg-path-editor/commits/gh-pages/ , you can still download one of them and open it locally.
