### ISSUE TITLE
Could the src/lib be exported as an NPM package ? 

### ISSUE THREAD

**Issue by gcornut** [Yqnn/svg-path-editor#146]
The tools in `src/lib` would be very useful as an NPM package. 

Do you have any plan to do so ?

**Comment by farskid** [comment]
I was actually thinking about the same idea and I could really use SVG path editor's functionalities as an NPM package.
@Yqnn I'd more than happy to open a PR and do get the work started. Any concerns or objections?

**Comment by Yqnn** [comment]
I'm on it.

Unfortunately it seems the `svg-path-editor` name has been taken 4 days ago to awkwardly publish  stuffs.
I will use `svg-path-editor-lib` instead.

**Comment by Yqnn** [comment]
Doc is incomplete, but it's ready for use :) :
https://www.npmjs.com/package/svg-path-editor-lib

 I tested it only in with ESM modules, but I expect it to also with CJS modules.

**Comment by farskid** [comment]
@Yqnn Awesome! I'll give it a go and get back with potential feedback. Thanks for your prompt effort.
