### ISSUE TITLE
Request to add further minifying to the minify function.

### ISSUE THREAD

**Issue by bglynch** [Yqnn/svg-path-editor#15]
## Request to add further minifying to the minify function.
First of all, this is a great tool, thank you for making it.

From looking at the code it seems that minifying is done on Line 510 in file 'svg.ts':
`str.replace(/^([a-z]) /i, '$1').replace(' -', '-');`

I would like to remove leading zero's on floats and leading whitespace before a negative number by changing the regex.
`str.replace(/ ?([a-z]) /gmi, '$1').replace(/ -/gmi, '-').replace(/-0\./gmi, '-.');`

### Example
Current Path of Minified Sword Logo
`M4 8l6-7l3-1l-1 3l-7 6c1 1 1 2 2 1c0 1 1 2 0 2a1.42 1.42 0 01-1 1a5 5 0 00-2-3q-0.5-0.1 -0.5 0.5t-1.5 1.3t-0.8-0.8t1.3-1.5t0.5-0.5a5 5 90 00-3-2a1.42 1.42 0 011-1c0-1 1 0 2 0c-1 1 0 1 1 2m6-7l0 2l2 0l-1.8-0.2l-0.2-1.8`

Path of Minified Sword Logo after additional minifying
`M4 8l6-7l3-1l-1 3l-7 6c1 1 1 2 2 1c0 1 1 2 0 2a1.42 1.42 0 01-1 1a5 5 0 00-2-3q-.5-.1-.5 .5t-1.5 1.3t-.8-.8t1.3-1.5t0.5-.5a5 5 90 00-3-2a1.42 1.42 0 011-1c0-1 1 0 2 0c-1 1 0 1 1 2m6-7l0 2l2 0l-1.8-.2l-.2-1.8`

**Comment by Yqnn** [comment]
Thanks for the suggestion!
It's included in last update.


Leading zero removal: `0.123` => `.123`
Space before dots after a decimal number : `1 0.123 0.123 0.123 1 0.123` => `1 .123.123.123 1 .123`
Bugfix: `Q -1 -1 -1 -1 Q -1 -1 -1 -1` was transformed to `Q-1-1 -1 -1Q-1-1 -1 -1`  is now transformed to `Q-1-1-1-1Q-1-1 -1-1`
