### ISSUE TITLE
Lock viewport configuration

### ISSUE THREAD

**Issue by steodor** [Yqnn/svg-path-editor#18]
Hi, first of all this is awesome work! Incredibly useful for editing paths, especially for creating/tweaking custom svg icons in my case. Hopefully with this issue i can help with a small improvement:

Currently, whenever editing the Path code in the top panel, the viewport Configuration updates itself automatically. While generally useful and an obvious default, this behavior is less desirable for me as i'd love the viewport to remain fixed at xy=0/0 and 24px height no matter what i do with the path. I find myself very frequently resetting the configuration and it's getting tedious.

**Proposal**: i would love it if the Configuration panel had a "lock" toggle icon which would prevent any subsequent automatic viewport configurations to be applied. It's debatable if it should also disable the input fields or not, i.e. also prevent manual updates while locked. Personally in my use-case i'd go with not, so manual changes would be allowed, only automatic ones prevented, but problem is then the functionality would be less obvious. Disabling the fields would make it crystal clear as to what the lock does, to any user.

Initially the toggle would be in the unlocked state, preserving the existing default behavior. Thus the lock would be an opt-in feature.

This lock would fit quite nicely in the existing Configuration panel, like this:
![image](https://user-images.githubusercontent.com/4397338/99502628-028bb980-2986-11eb-8dbb-16a2b6da66f1.png)

I could have a go at implementing this and submitting a pull request if you confirm that it's something you would consider integrating in the live version. Please let me know what you think :)

**Comment by steodor** [comment]
@Yqnn any thoughts on this?

**Comment by Yqnn** [comment]
I totally agree with that, it's actually something that is on my todo list.

I'm wondering if I could be implemented in a more seamless way: automatically update the viewport only if the path doesn't fit in it.
The button could also be added in the toolbar proposed in PR #19 .

**Comment by steodor** [comment]
Cool, i'll leave it to you then, at least until the toolbar is integrated into the project so that this doesn't get worked on twice.

Until then, really awesome project! I love the simplicity because it focuses you on controlling the paths. Please don't lose that by trying to make it more accessible to people who don't know SVG basics :))

**Comment by Yqnn** [comment]
Done in PR #20
