### ISSUE TITLE
Translate does nothing in Relative mode

### ISSUE THREAD

**Issue by salty-horse** [Yqnn/svg-path-editor#2]
The "Translate" operation only works in Absolute mode.

If you're in Relative mode, and choose to translate by e.g., (1,1), it does nothing. Is there a reason why it shouldn't work?

**Comment by Yqnn** [comment]
The only case where a relative command is affected by a translation, is when it's the first one of the path : in that case, it's equivalent to an absolute command.

And Indeed, this particular case is not supported. I'm preparing a fix :)
