### ISSUE TITLE
Similar work

### ISSUE THREAD

**Issue by danmarshall** [Yqnn/svg-path-editor#23]
Hello, thank you for creating this amazing tool, which I have been wanting for a long time! I'm glad I found it.
FYI I also found a similar tool here: 

https://github.com/mathieudutour/svg-path-visualizer

Cheers

**Comment by Yqnn** [comment]
Funny that the 2 tools were released the same week  :blush:

There are similarities, but as Matthieu said, the purpose of the 2 tools is different, one is for beginner to learn how pathes work, and the other is for advanced users to create or fine tune a path.
