### ISSUE TITLE
Shortcuts converts

### ISSUE THREAD

**Issue by arcanis** [Yqnn/svg-path-editor#27]
Really nice tool! As a workaround for #21 I'm currently reworking all the points (removing extraneous points, turning `l` into `h` when they are almost horizontal, etc), but it's a bit heavy on the fingers at the moment. Would you consider adding shortcuts to simplify this? For instance (picked U & I since they seem fairly safe for web applications, are next to each other, and `I` is a vertical line):

- `Ctrl-U`: Convert to horizontal
- `Ctrl-I`: Convert to vertical
- Delete: Remove the selected point

**Comment by Yqnn** [comment]
Indeed that would be very useful.
I will implement the `Delete`for sure.

For the command conversion, I'm wondering if it wouldn't be better to change the behaviour of the existing shortcuts.
Today pressing `m` inserts a relative move command, and pressing `Shift-m` inserts an absolute move command (same with `l`, `h`, `v`, `c`, etc.).
When creating a path, using relative command doesn't really make sense, as it's very hard to manipulate.
Instead we could use `m` to insert an **absolute** move command, and `Shift-m` would convert the selected command to a move command (same with `l`, `h`, `v`, `c`, etc.)

**Comment by Yqnn** [comment]
Conversion and Delete shortcuts added.
