### ISSUE TITLE
Enhancement-Feature Request: Flip & Rotate

### ISSUE THREAD

**Issue by Vinorcola** [Yqnn/svg-path-editor#34]
Hi, awesome tool!

I'm missing a horizontally/vertically flipping operation. Or maybe a rotation action (90°/180°/270° - I reckon other angles are much more diffcults)

**Comment by Yqnn** [comment]
Hi,

Some of these operations are already supported:
- Horizontal flip: ScaleX=-1
- Vertical flip: ScaleY=-1
- 180 rotate: ScaleX=-1, ScaleY=-1

**Comment by Vinorcola** [comment]
Oh! Nice. I have not thought about the negative scale ^^

Thank you!
