### ISSUE TITLE
Add more basic transform tools such as rotate and reflect

### ISSUE THREAD

**Issue by justingolden21** [Yqnn/svg-path-editor#36]
Hi, absolutely love your tool.

Adding reflect horizontal / vertical, as well as maybe rotate would probably be helpful for a number of users.

You could add it under "path operations" with scale and translate, and then you'd have just about all of the basics.

**Comment by Yqnn** [comment]
Hello,

Horizontal/Vertical reflect is already possible via scaleX:-1 or scaleY:-1  (and rotate 180 via scaleX:-1 and scaleY:-1).
Other types of rotation could be added in a future improvement.

**Comment by justingolden21** [comment]
Got it, I forgot about that, thank you. I was thinking a note somewhere for users about this could be useful, but idk where is put it. Maybe if you had a few things like this you could add them to a FAQs modal or something

**Comment by justingolden21** [comment]
Hi, would you be interested in adding a mode that automatically reflects (horizontally/vertically) like a kaleidoscope mode?

In other words, when you change a path on the left, it reflects and changes on the right.

I could paypal you a bit to implement this if you'd be interested, as I know it's kind of a niche feature that may take some time to implement, but I could use it for a project.

Thank you,

Justin

**Comment by danielwerg** [comment]
> In other words, when you change a path on the left, it reflects and changes on the right.

Was about to open an issue and suggest that :O
Would love to see that feature in the editor!

**Comment by abvgdeyoj** [comment]
Mirroring would be very useful.
