### ISSUE TITLE
Compress path data - remove spaces

### ISSUE THREAD

**Issue by Danny-Engelman** [Yqnn/svg-path-editor#4]
Great tool!

But I still have to post-process your output.

Could you take out the spaces from the processed data

**Your output:**
````
m 555 730 h -99 a 10 10 0 0 0 0 21 h 99 a 10 10 0 0 0 0 -21 z m 0 30 h -99 a 10 10 0 1 0 0 21 h 99 a 10 10 0 0 0 0 -21 z m
````

**What you want in SVG:**
````
m555 730h-99a10 10 0 0 0 0 21h99a10 10 0 0 0 0-21zm0 30h-99a10 10 0 1 0 0 21h99a10 10 0 0 0 0-21zm
````

**Comment by Yqnn** [comment]
Indeed, it's something very usefull.
Done 8e3b325b67ffb6c41c70b63ee799ebe6a25b7077
