### ISSUE TITLE
Cannot access site

### ISSUE THREAD

**Issue by softmarshmallow** [Yqnn/svg-path-editor#42]
<img width="1675" alt="Screen Shot 2021-09-28 at 3 53 20 AM" src="https://user-images.githubusercontent.com/16307013/134967941-935f3b74-9846-4dd3-ad20-228663d7095e.png">

Seems like site is dead for some reason. can you confirm this?

**Comment by yann-armelin** [comment]
Is there any error displayed in the browser console ?

**Comment by Yqnn** [comment]
Issue closed:
- no additional information provided
- not reported by any other user.
- workaround proposed
