### ISSUE TITLE
icon is not showing in Safari 15.1

### ISSUE THREAD

**Issue by YeeJiaWei** [Yqnn/svg-path-editor#48]
<img width="1437" alt="Screenshot 2021-11-28 at 4 18 13 PM" src="https://user-images.githubusercontent.com/21292986/143734987-259ecc66-abf8-4c0a-ab40-a9df02b67f1c.png">

**Comment by Yqnn** [comment]
Not issue on my side with Safari 15.1 .

What you can try:
 - Check that you have no extension blocking custom fonts (Material Icons are coming from a custom font).
 - Force page refresh: ⌘ + R
 - Clear Safari cache (Develop menu has to be activated first in preferences):  ⎇ + ⌘ + E

**Comment by YeeJiaWei** [comment]
I have tried with your suggestion, but the icon still not showing up.

I also check the custom font, it have been loaded also
<img width="300" alt="Screenshot 2021-11-29 at 11 33 20 AM" src="https://user-images.githubusercontent.com/21292986/143804612-280ee90b-6414-49f9-932f-85f837c75637.png">

**Comment by Yqnn** [comment]
What's really weird on your screenshot, is that few icons are working well: `arrow_left`, `expand_more` and `lock_open` .
They are based on the same font-family as the other icons.

If you open that page, can you see all the icons ?
https://fonts.google.com/icons

**Comment by YeeJiaWei** [comment]
Yea, every icon are showing good.

<img width="1440" alt="Screenshot 2021-12-08 at 1 05 22 AM" src="https://user-images.githubusercontent.com/21292986/145073998-ed90e6ad-7dfe-43fc-9c66-ce327632f126.png">

**Comment by Yqnn** [comment]
Ok, I managed to reproduce the issue.
it's actually due to the following accessibility option:
![image](https://user-images.githubusercontent.com/588624/146460185-b0d12c15-345e-4106-9eb9-68c9a967aa81.png)
