### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by macgile** [Yqnn/svg-path-editor#49]
Hi, great work !
importing background image works fine.
On the other hand, it becomes impossible to add or modify the existing path.
It seems that the image is in the foreground and the path in the background.

best regards

**Comment by Yqnn** [comment]
Hello,
You have to deactivate the image editing mode, by clicking on "Toggle image management mode" (blue icon, top right)

**Comment by macgile** [comment]
Hello,

It's work fine :)

Thank's

best regards
