### ISSUE TITLE
Use image as template for tracing

### ISSUE THREAD

**Issue by EvelynSubarrow** [Yqnn/svg-path-editor#6]
Being able to put an image underneath the current path could make this great for tracing paths, ideally the position and scale could be controlled

**Comment by RoucherA** [comment]
Hey, I'm working on a project where I have to edit svgs, and this feature is essential for me. I can give some time to help you with development (but I'm still new to Node.js and don't really understand the project architecture for now ^^).

**Comment by Yqnn** [comment]
I agree that would be great.

There are 2 approaches to implement this:
 - user upload the image: that would require a real webserver, or a third party service to store it
 - user enters a URL: less user friendly, but much simpler and feasible


@RoucherA Node.js knowledge is not needed, the app is based on [angular](https://angular.io/) framework.

**Comment by isakkeyten** [comment]
@Yqnn user can select an image which we can then convert it to base64 and embed it as such in the svg canvas
https://codesandbox.io/s/local-image-to-base64-0rogq?file=/src/App.js
example is in react but i assume it shouldn't be that much different in angular
