### ISSUE TITLE
Scroll wheel is too sensitive

### ISSUE THREAD

**Issue by Ciantic** [Yqnn/svg-path-editor#62]
From Windows 10 settings my mouse wheel has 7 rows per click.

I think the scroll wheel zoom is too sensitive, it should ignore that setting. E.g.

Take this:
![image](https://user-images.githubusercontent.com/64731/154703056-30de0b31-5f16-4842-bf21-f6df60998171.png)

I flip scroll wheel only once, and I have no idea where I am after that:
![image](https://user-images.githubusercontent.com/64731/154703137-2b37c3b3-ff9b-4ef5-b918-7eac5cc86b8f.png)

It's possible to ignore mouse wheel setting and use singe clicks, I suggest you find a way.

Cool project!

**Comment by Yqnn** [comment]
Which browser are you using ?
Usually it's Firefox that is the most eccentric on that topic.

Scroll wheel behaviour has always been inconsistant between browsers, OS and devices. 
There used to be some crazy workarounds: https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers , but not sure I want to go in that direction ...


Meanwhile you can deactivate it using the following button:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/588624/154808490-29496ca4-e0f6-4056-a92f-44e8a2ce7387.png">

**Comment by Ciantic** [comment]
It's Google Chrome, if I open `about:blank` and use wheel event like this:

```
document.querySelector("body").addEventListener("wheel", e => console.log(e));
```

I get a single value like this:

```WheelEvent {isTrusted: true, deltaX: -0, deltaY: -466.6666564941406, deltaZ: 0, deltaMode: 0, …}```

and if I flip it up I get single value like this:

```WheelEvent {isTrusted: true, deltaX: -0, deltaY: 466.6666564941406, deltaZ: 0, deltaMode: 0, …}```

Rest of the parameters omitted.

My wheel works correctly, it send single WheelEvent per click, I think one should read just the direction, and not use the `deltaY`.

**Comment by Yqnn** [comment]
Reading only the direction of the WheelEvent is not an option: a trackpad can generate more than 100 events per second.
Relying on deltaY is actually key to obtain a precise and smooth scrolling. Even on a traditional mouse, if inertia scrolling is enabled (default behavior on macOS).

The simplest option I see, is to limit the deltaY value. Something like 80 should be ok.
I will do some tests in that direction.
