### ISSUE TITLE
Add URL query string param: `...?path=M 10 10`

### ISSUE THREAD

**Issue by broccolihighkicks** [Yqnn/svg-path-editor#70]
Is it possible to use a URL query string to encode a path, which then opens in the editor?

This way any path can be opened in the web editor from any location.

Path's can then also be shared.

For large paths, gzip could also be used (`path_gzip=x`) (https://www.typescriptlang.org/play does this).

Thanks.

**Comment by Danny-Engelman** [comment]
+1
I am also referring to this editor from StackOverflow, would be cool to include the d-path
