### ISSUE TITLE
Add cursor pointer absolute X/Y position

### ISSUE THREAD

**Issue by broccolihighkicks** [Yqnn/svg-path-editor#72]
This would be useful when debugging points.

**Comment by hanbin9775** [comment]
Hi. Anyone working on this issue? If not I would like to make pr on this issue.

**Comment by ntsd** [comment]
Probably help https://github.com/Yqnn/svg-path-editor/pull/111

**Comment by Yqnn** [comment]
Done in #111 and #115 .
