### ISSUE TITLE
The editor take a long time to load

### ISSUE THREAD

**Issue by Whip** [Yqnn/svg-path-editor#77]
I'm not sure if its just me or happens to everyone but it takes around 5 minutes for the editor (https://yqnn.github.io/svg-path-editor/) to even start loading. It didn't used to be like this. Can this be resolved?

**Comment by Yqnn** [comment]
I reproduced that once in Chrome, then I just pressed refresh and it was quick again.
The resources of the page are only 500 KB, so even on a slow connection it shouldn't be that long.
I guess it was a sporadic issue of Github.

Apart from hosting the page somewhere else than Github, I don't think there is something to do.


Do you still face the issue ? Did you try several browsers ? Or another network ?

**Comment by Whip** [comment]
Okay I tried using Firefox and it loads instantly so it may be a Chrome specific issue. I also noticed in the status bar, it says "Waiting for play.google.com...". Maybe that gives you a clue.

**Comment by Yqnn** [comment]
It could be a Chrome plugin that is trying to load something before displaying the page.

According to that [reddit post](https://www.reddit.com/r/chrome/comments/oue3bu/waiting_for_playgooglecom/), emptying Chrome caches may resolve the issue.

**Comment by Whip** [comment]
Disabled all extensions and cleared all cache and cookies. Didn't work. I did find a workaround though, when its endlessly loading, if you press Enter on the URL bar again, it skips whatever it was stuck on and loads the page instantly. Maybe it helps someone.

**Comment by alexandernst** [comment]
I can repro this from time to time, maybe once a week. Screenshot below.

It seems that it's trying to fetch something from gstatic.com and it's taking an unusual amount of time. The weird thing is that hitting "Esc" to cancel all requests and then hitting "Enter" (while the URL bar is focused) seems to fix the issue (and then I ca't repro it for another week).

<img width="1505" alt="Cursor_y_Nueva_pestaña" src="https://user-images.githubusercontent.com/89727/179326774-b7adb054-3dcf-4081-988d-3a2bd5c26d85.png">

**Comment by Yqnn** [comment]
It looks like there is something wrong in the service workers (needed for the PWA setup).
I will investigate.

**Comment by Yqnn** [comment]
I've done a little fix in the PWA setup (for the record: https://stackoverflow.com/questions/55473561/angular-service-worker-ignores-relative-path ).

You may encounter the issue once more (due to PWA cache), then hopefully it should be not occur anymore.
