### ISSUE TITLE
Aspectratio

### ISSUE THREAD

**Issue by meelix** [Yqnn/svg-path-editor#78]
The aspect ratio is fixed to about 4:2.9. Since there's an input for the viewport width and height it should be adjustable or preserving aspect ratio is toggleable.

**Comment by Yqnn** [comment]
The aspect ratio is not fixed: it takes all the available space.

If the browser window is resized: the width is preserved, and the height is adjusted to match the window height.
And if the viewport height is changed, it's the width that is automatically adjusted.

I don't really see any advantage of deactivating the preservation of the aspect ratio.

**Comment by meelix** [comment]
Ah, yes makes sense. Didn't think of that

I just had to add a specific path to an existing svg and somehow forgot that i should just start at 0,0 and enter the corresponding coordinates
