### ISSUE TITLE
Shareable Path Urls

### ISSUE THREAD

**Issue by pedropsi** [Yqnn/svg-path-editor#86]
Hi Yann, a suggestion - it would be nice to have shareable urls. While this could of course be extended to all parameters, having just the path would already be extremely useful for collaborating more easily.

So opening an url like this:
https://yqnn.github.io/svg-path-editor?path=M 13 0 L 13 1 L 13 2 C 14 5 12 12 8 14 C 6 12 2 12 0 16 C -3 22 5 28 10 23 C 12 21 12 16 9 15 C 12 13 15 8 15 3 C 16 4 20 9 19 14 C 16 13 13 15 13 18 C 13 27 25 27 25 18 C 25 15 22 13 20 14 C 21 9 18 3 15 1 C 15 1 15 0 15 0 C 15 0 14 0 13 0 Z 

... would automatically load the path (in this case, it's a cherry).

At the same time, editing the path would automatically update the url (always kept in sync).

If you feel this feature aligns with your goals for the SVG Path Editor, I wouldn't mind trying to make a pull request at some point or simply provide some tips for your own implementation

**Comment by Yqnn** [comment]
That's already supported: use the 'share' button on top right.
