### ISSUE TITLE
Feature Request: Split command into two

### ISSUE THREAD

**Issue by sunnygoyal** [Yqnn/svg-path-editor#99]
Provide ability to split a command into two, by inserting a new point in the middle.
This is useful when trying to match two path commands for morphing

**Comment by Yqnn** [comment]
That's already supported: click on the previous point, then  **...** > **Insert After** > **Line to** or just press **L** on keyboard.

https://user-images.githubusercontent.com/588624/224789560-a1a381a9-dcff-4702-91f7-bd332073dbad.mp4

**Comment by sunnygoyal** [comment]
My request is a different than what is mentioned above. What I am requesting is splitting the existing curve into half without modifying it visually:
https://stackoverflow.com/questions/18655135/divide-bezier-curve-into-two-equal-halves


All the existing methods add a new curve at the end and any manual cursor dragging ends up changing the image
